---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  vars:
    # Define 'legacy' and 'clusterid' as needed in your inventory or extra_vars

  tasks:
    - import_role:
        name: checkjob

    - name: Filter legacy based on clusterid
      set_fact:
        filtered_legacy: >-
          {{
            legacy if ((clusterid | default('all')) | lower == 'all')
            else (
              legacy
              | selectattr('clusterid', 'in',
                  (clusterid if clusterid is iterable and clusterid is not string
                   else [clusterid | int])
                )
              | list
            )
          }}

    - name: Generate legacy container add API request
      set_fact:
        cont_list: >
          {"context":"MANAGEDOBJECTS_NODE","action":"MANAGEDOBJECTS_NODE_ADD","actionObject":{"dgInfo":[
            {%- for item in filtered_legacy %}
              {% for c in item.containers %}
                {% if c.sigcardid not in ( '110','38','39','32','33') %}
                  {"cardDetails":[{"SIGNALINGCARD_NAME":"{{ c.name }}","CHASSISID":"{{ item.chassisid }}","IPADDRESS":"{{ c.interface[0].ip }}","CLUSTERID":"{{ item.clusterid }}","HOSTNAME":"{{ c.name }}","NODETYPE":{% if c.sigcardid == "101" or c.sigcardid == "102" %}1{% else %}{{c.nodetype }}{% endif %},{% if (c.sigcardid == "32") and (c.nodetype == 1) %}"MAXSUBSCRIBERSRANGE":"10000"{% endif %}},],"DGID":"{{ c.dgid }}","DGNAME":"{% if c.sigcardid == '101' or c.sigcardid == '102' %}{{ c.name }}{% else %}{{ c.cardtype}}{% endif %}","CARDTYPE":"{{ c.sigcardid }}"},
                {% endif %}
              {% endfor %}
            {% endfor -%}
          ]}}


    - set_fact:
        cont_list: "{{cont_list['actionObject']['dgInfo']}}"

    - debug:
        msg: "{{ cont_list }}"

    - name: MANAGEOBJECTS_NODE_ADD
      uri:
        url: "http://{{ cmsurl }}/cms/config?v=1618385170120"
        method: POST
        headers:
          Connection: 'keep-alive'
          Authorization: 'Bearer {{ cms_login_token }} '
          Accept: 'application/json, text/plain, */*'
        validate_certs: no
        body: '{{ cont_list }}'
        timeout: 1200
        body_format: json
      register: create_container
      failed_when: create_container.json.code | int not in [200, 201]

    - debug:
        msg: "{{ create_container }}"
