---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - block:
        - name: Generate add microservice containers request
          set_fact:
            rhelidm_node: >
               {"rhelidm_list":[
                    {% for item in rhelidm_servers %}
                     {% for c in item.containers %}
                        {% for ifc in c.interface if ifc.subnet_type == 'oam' %}
                        {"context":"MICROSVC_CARDCONFIG","action":"MICROSVC_CARDCONFIG_ADD","actionObject":[{"INSTANCE_TYPE":"{{ c.name }}","NO_OF_INSTANCE":1,"VERSION":"{{ c.version }}","CLUSTERID":"{{ item.clusterid }}","CHASSISID":"{{ item.chassisid }}","INSTANCE_IPADDRESS":"{{ ifc.ip }}","INSTANCE_HOSTNAME":"{% if c.host is defined %}{{ c.host }}{% endif %}"{% if c.pttid is defined %},"INSTANCE_PTTSERVERID":"{{ c.pttid }}"{% endif %}}]},
                        {% endfor %}
                     {% endfor %}
                    {% endfor %}
                    ]}
        
        
        - debug:
            msg: "{{ rhelidm_node }}"
        
        
        - name: Add microservice containers
          uri:
             url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: "{{ item }}"
             timeout: 600
             body_format: json
          register: add_container_resp
          with_items: "{{ rhelidm_node | json_query('rhelidm_list[]') }}"
          when: dry_run == 0
          failed_when: add_container_resp.json.code | int not in [200, 201]
        
        - debug:
            msg: "{{ add_container_resp  }}"
        
        - name: update the task in status file
          lineinfile:
              path: "{{status_file}}"
              line: "add_rhelidm_containers"
        
      when: "'add_rhelidm_containers' not in status_check_list"
