---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - block:
        - name: Get networkmap details
          include_tasks: get_networkmap_details.yml
        
        - set_fact:
            resp: "{{ get_networkmap | json_query('json')|to_json|from_json }}"
        
        - set_fact:
            aa: "{{ resp | json_query(query1) }}"
          vars:
            query1: "dgInfo[?CONTAINERNAME=='POC Server'].DGID"
        
        - set_fact:
            bb: "{{ resp | json_query(query2)}}"
          vars:
            query2: "dgInfo[?CONTAINERNAME=='POC Server'].cardDetails"
        
        - set_fact:
            filter: "{{bb | json_query('[]')}}"
        
        - set_fact:
            ptt_id: "{{filter | json_query(query3) | unique}}"
          vars:
            query3: "[?CONTAINERNAME=='POC Server'].PTTSERVERID"
        
        - name: Subscriber capacity array substitution
          set_fact:
            subs_get: >
              {"capacity_get":[
               {% for item in ptt_id %}
                {% for a in aa%}
                {"context":"POCSUBSCRCAPACITYCONFIG","action":"POCSUBSCRCAPACITYCONFIG_UPDATE","actionObject":{"PTTSERVERID":"{{item}}","ALLOWSUBSCRPROVISIONING":1,"MAXSUBSCRIBERSRANGE":{{ subs_capacity }},"MAXSUBSCRIBERS":{{ subs_capacity }},"fieldRanges":{"contextValues":["MAXSUBSCRIBERS"],"ranges":["1-10000"]}},"object":{"dgId":"{{a}}"}},
                {% endfor %}
               {% endfor %}
              ]}
        
        - debug:
            msg: "{{subs_get|to_json|from_json|json_query('capacity_get')}}"
        
        - name: POCSUBSCRCAPACITYCONFIG_UPDATE
          uri:
             url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: '{{item}}'
             body_format: json
          register: subscriber_capacity
          with_items:  "{{subs_get|to_json|from_json|json_query('capacity_get')}}"
          when: dry_run == 0
          failed_when: subscriber_capacity.json.code | int not in [200, 201]
        
        - name: update the task in status file
          lineinfile:
              path: "{{status_file}}"
              line: "configure_subscapacity"
      when: "'configure_subscapacity' not in status_check_list"
