---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - block:

        - name: Get networkmap details
          include_tasks: get_networkmap_details.yml
        
        - set_fact:
            resp: "{{ get_networkmap | json_query('json.dgInfo')|to_json|from_json }}"
        
        
        - name: Extracting POC servers
          set_fact:
            servers: >
             {% for server in get_networkmap.json.dgInfo %}{% if server.CARDTYPE == 32 %}{{server}},{% endif %}{% endfor %}
        
        - name: APNPROFILEINFO_GETALL
          uri:
            url: "http://{{ cmsurl }}/cms/config?v=1621877645057"
            method: POST
            headers:
              Connection: 'keep-alive'
              Authorization: 'Bearer {{ cms_login_token }} '
              Accept: 'application/json, text/plain, */*'
            validate_certs: no
            body:
              {"context":"APNPROFILEINFO","action":"APNPROFILEINFO_GETALL","object":{"dgId":"{{ item.DGID}}"}}
            body_format: json
          loop: "{{servers}}"
          register: apn
          failed_when: apn.status not in [200, 201]
        
        - set_fact:
            apn_id: "{{ apn.results |to_json| from_json | json_query('[].json.data.additionalData1[]') }}"
        
        - set_fact:
            cont: "{{ apn.results |to_json| from_json | json_query('[].item') }}"
        
        - set_fact:
            apn_profile: >
              {"apn":[
               {% for i in apn_id if i.APNID == apnid|int %}
               {% for id in cont %}
                {"context":"APNPROFILEINFO","action":"APNPROFILEINFO_UPDATE","actionObject":{"MCSXCAPROOTURI":"{{'wms'~wildcard}}","GEO_SIPPROXYURI":"{{id.DGNAME|lower~'g'~wildcard}}","KMSWSURI":"{{'kms'~wildcard}}","SIPPROXYURI":"{{id.DGNAME|lower~wildcard}}","PTTBUCKETURICELL":"https://msgstore{{wildcard}}/ptxdata","APNID":{{i.APNID}},"LOCDATAURICELL":"https://syncloc{{wildcard}}/ptxdata","CLIENTLOGURI":"{{'rls'~wildcard}}","GEOREG_GEOF5URI":"{{id.DGNAME|lower~'gntfy'~wildcard}}","DYNAMICQOSFLAG": 0,"GEOREG_PRIMF5URI":"{{id.DGNAME|lower~'ntfy'~wildcard}}","XCAPROOTURI":"{{'wms'~wildcard}}","OIDCXCAPROOTURI":"{{'wms'~wildcard}}","PTXBUCKETURICELL":"https://msgstore{{wildcard}}/ptxdata","APNNAME":"{{i.APNNAME}}","ISDEFAULT": {{i.ISDEFAULT}},"PTTSERVERID":"{{id.cardDetails[0].PTTSERVERID}}"},"object":{"dgId":"{{id.DGID}}"}},
               {% endfor %}
               {% endfor %}
                ]}
        
        - name: POC APNPROFILEINFO UPDATE
          uri:
             url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: '{{item}}'
             body_format: json
             status_code: 200
          with_items: "{{apn_profile|to_json|from_json|json_query('apn')}}"
          register: poc_upd
          when: dry_run == 0
          failed_when: poc_upd.json.code | int not in [200, 201]
        
        #----------------------------------------------------------------------------------------------------------------------------
        
        - name: Extracting XDM servers
          set_fact:
            servers: >
             {% for server in get_networkmap.json.dgInfo %}{% if server.CARDTYPE == 36 %}{{server}},{% endif %}{% endfor %}
        
        - name: APNPROFILEINFO_GETALL
          uri:
            url: "http://{{ cmsurl }}/cms/config?v=1621877645057"
            method: POST
            headers:
              Connection: 'keep-alive'
              Authorization: 'Bearer {{ cms_login_token }} '
              Accept: 'application/json, text/plain, */*'
            validate_certs: no
            body:
              {"context":"APNPROFILEINFO","action":"APNPROFILEINFO_GETALL","object":{"dgId":"{{ item.DGID}}"}}
            body_format: json
          loop: "{{servers}}"
          register: apn
          failed_when: apn.status not in [200, 201]
        
        - set_fact:
            apn_id: "{{ apn.results |to_json| from_json | json_query('[].json.data.additionalData1[]') }}"
        
        - set_fact:
            cont: "{{ apn.results |to_json| from_json | json_query('[].item') }}"
        
        - set_fact:
            apn_profile: >
              {"apn":[
               {% for i in apn_id if i.APNID == apnid|int %}
               {% for id in cont %}
                {"context":"APNPROFILEINFO","action":"APNPROFILEINFO_UPDATE","actionObject":{"MCSXCAPROOTURI":"{{'wms'~wildcard}}","GEO_SIPPROXYURI":"","KMSWSURI":"{{'kms'~wildcard}}","SIPPROXYURI":"","PTTBUCKETURICELL":"https://msgstore{{wildcard}}/ptxdata","APNID":{{i.APNID}},"LOCDATAURICELL":"https://syncloc{{wildcard}}/ptxdata","CLIENTLOGURI":"{{'rls'~wildcard}}","GEOREG_GEOF5URI":"","DYNAMICQOSFLAG": 0,"GEOREG_PRIMF5URI":"","XCAPROOTURI":"{{'wms'~wildcard}}","OIDCXCAPROOTURI":"{{'wms'~wildcard}}","PTXBUCKETURICELL":"https://msgstore{{wildcard}}/ptxdata","APNNAME":"{{i.APNNAME}}","ISDEFAULT": {{i.ISDEFAULT}},"PTTSERVERID":"{{id.cardDetails[0].PTTSERVERID}}"},"object":{"dgId":"{{id.DGID}}"}},
               {% endfor %}
               {% endfor %}
                ]}
        
        
        - name: XDM APNPROFILEINFO UPDATE
          uri:
             url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: '{{item}}'
             body_format: json
             status_code: 200
          with_items: "{{apn_profile|to_json|from_json|json_query('apn')}}"
          register: xdm_upd
          when: dry_run == 0
          failed_when: xdm_upd.json.code | int not in [200, 201]
        
        - set_fact:
            push_profile: >
              {"push":[
                {% for i in resp if i.CARDTYPE == 32 or i.CARDTYPE == 36 %}
                  {"context":"APNPROFILEINFO","action":"APNPROFILEINFO_PUSH","actionObject":{"APNID":{{apnid}}},"object":{"dgId":"{{i.DGID}}"}},
                {% endfor %}
              ]}
        
        - debug:
            msg: "{{push_profile|to_json|from_json|json_query('push')}}"
        
        - name: APNPROFILEINFO_PUSH
          uri:
             url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: '{{item}}'
             body_format: json
             status_code: 200
          with_items: "{{push_profile|to_json|from_json|json_query('push')}}"
          register: apn_push
          when: dry_run == 0
          failed_when: apn_push.json.code | int not in [200, 201]
        
        - name: update the task in status file
          lineinfile:
              path: "{{status_file}}"
              line: "configure_apn"
        	  
      when: "'configure_apn' not in status_check_list"
