---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - block:
        - name: Get networkmap details
          include_tasks: get_networkmap_details.yml
        
        - set_fact:
            dgInfo: "{{ get_networkmap |json_query('json.dgInfo')|to_json |from_json  }}"
        
        - debug:
            msg: "{{ dgInfo }}"
        
        - set_fact:
            subnets1: >
               {"iplist":[
                  {% for item in dgInfo %}
                   {% for c in item.cardDetails %}
                    {% for nw in rhelidm_servers %}
                      {% for ip in nw.containers if nw.clusterid|string() == c.CLUSTERID|string() %}
                       {% for if in ip.interface if (ip.sigcardid|string() == c.SIGNALINGCARDTYPE|string() and ip.dgid|string() == item.DGID ) %}
                          {
                          "context": "SIGNALINGCARDALIASIPINFO",
                          {% if if.subnet_type == 'oam' %}
                          "action": "SIGNALINGCARDALIASIPINFO_UPDATE",
                          {% else %}
                          "action": "SIGNALINGCARDALIASIPINFO_ADD",
                          {% endif %}
                          "actionObject":[{
                              "BROADCAST_ADDRESS": "{{ if.broadcast }}",
                              "ENABLE_ARP_INTERFACE": 1,
                              "FQDN": "{{ ip.host }}",
                              "INTERFACE_DEVICE": "{{ if.interface }}",
                              "IPADDRESS": "{{ if.ip }}",
                              "IPADDRESS_TYPE": "1",
                              "IPV6ADDRESS": "",
                              "NETMASK_ADDRESS": "{{ if.netmask }}",
                              "PTTSERVERID": "{{ c.PTTSERVERID }}",
                              "SIGNALINGCARDID": "{{ c.SIGNALINGCARDID }}",
                              {% if if.subnet_type == 'oam' %}
                              "SUBNETTYPE": "2",
                              {% elif if.subnet_type == 'service' %}
                              "SUBNETTYPE": "0",
                              {% elif if.subnet_type == 'log' %}
                              "SUBNETTYPE": "3"
                              {% endif %}
                          }],
                          "object": {
                              "dgId": "{{ ip.dgid }}"
                          }
                      },
                         {% endfor %}
                        {% endfor %}
                       {% endfor %}
                     {% endfor %}
                    {% endfor %}
               ]}
        
        - debug:
              msg: "{{ subnets1 }}"
        
        
        - name: SIGNALINGCARDALIASIPINFO_ADD
          uri:
             url: "http://{{ cmsurl }}/cms/config?v=1618385170120"
             method: POST
             headers:
               Connection: 'keep-alive'
               Authorization: 'Bearer {{ cms_login_token }} '
               Accept: 'application/json, text/plain, */*'
             validate_certs: no
             body: "{{ item }}"
             body_format: json
          register: sig_card_add
          with_items: "{{ subnets1| json_query('iplist[]') }}"
          when: dry_run == 0
          failed_when: sig_card_add.json.code | int not in [200, 201]
        
        - name: update the task in status file
          lineinfile:
              path: "{{status_file}}"
              line: "configure_rhelidm_network"
        
      when: "'configure_rhelidm_network' not in status_check_list"
