---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - block:
        - name: Creating body for sending request
          set_fact:
            data: >
              {
                "context":"MICROSVC_GLOBAL_ATTR_VALUE_CONFIG",
                "action":"MICROSVC_GLOBAL_ATTR_VALUE_CONFIG_UPDATE",
                "object":{},
                "actionObject":[
                  {% for idx in range(2) %}
                    {"PARAMNAME":"ABDGFEATUREFLAG","PARAMVALUE":{{micro_common_config['ABDG_FEATURE_FLAG']}},"CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"AFFILIATION_MONITORING_FLAG", "PARAMVALUE":{{micro_common_config['AFFILIATION_MONITORING_FLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"CATUI_FQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"CORP_HIERARCHY", "PARAMVALUE":"{{micro_common_config['CORP_HIERARCHY']}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"DEVICE_SHARING_FEATURE_FLAG", "PARAMVALUE":{{micro_common_config['DEVICE_SHARING_FEATURE_FLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"DYNAPI_SERVICE_ENABLED", "PARAMVALUE":{{micro_common_config['DYNAPI_SERVICE_ENABLED']}}, "CLUSTERID":{{idx + 1}}},
                    {"PARAMNAME":"GCM_PUSH_NOTIFY", "PARAMVALUE":{{micro_common_config['GCM_PUSH_NOTIFY']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"GEOFENCE_ENABLED", "PARAMVALUE":{{micro_common_config['GEOFENCE_ENABLED']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"GOOGLE_MAPS_API_KEY", "PARAMVALUE": "{{global_micro_common_config[0]['GOOGLE_MAPS_API_KEY']}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"GRPMEM_LOC_SVC_ENABLED", "PARAMVALUE":{{micro_common_config['GRPMEM_LOC_SVC_ENABLED']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"IDM_SERVICE_FLAG", "PARAMVALUE":{{micro_common_config['IDM_SERVICE_FLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"IDM_WS_FQDN", "PARAMVALUE": "{{'https://wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"KEYCLOAK_EXTFQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"KEYCLOAK_PRIVATE_EXTFQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"KPNS_NOTIFYENCFLAG", "PARAMVALUE":{{micro_common_config['KPNS_NOTIFYENSFLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"LOCATION_SVC_ENABLED", "PARAMVALUE":{{micro_common_config['LOCATION_SVC_ENABLED']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"MOBILESYNCFLAG", "PARAMVALUE":{{micro_common_config['MOBILESYNCFLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"PRESENCE_SVC_ENABLED", "PARAMVALUE":{{micro_common_config['PRESENCE_SVC_ENABLED']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"PTXFEATUREFLAG", "PARAMVALUE":{{micro_common_config['PTXFEATUREFLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"QPPPTXFEATUREFLAG", "PARAMVALUE":{{micro_common_config['QPPPTXFEATUREFLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"RESOURCE_SVR_EXTERNAL_FQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"SGWR_IS_FILTERED_REPLICATION", "PARAMVALUE":{{micro_common_config['SGWR_IS_FILTERED_REPLICATION']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"UPSTREAM_DNS_SERVER_IP", "PARAMVALUE": "[{{global_micro_common_config[0]['UPSTREAM_DNS_SERVER_IP']}}]", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"VOICEMSGFALLBACKFLAG", "PARAMVALUE":{{micro_common_config['VOICEMSGFALLBACKFLG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"WCSR_FQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"XCAPMOBILESYNCFLAG", "PARAMVALUE":{{micro_common_config['XCAPMOBILESYNCFLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"WDS_EXTFQDN", "PARAMVALUE": "{{'wds'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"WDS_IDM_WS_FQDN", "PARAMVALUE": "{{'https://wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"WDS_KEYCLOAK_EXTFQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"WDS_RESOURCE_SVR_EXTERNAL_FQDN", "PARAMVALUE": "{{'wms'~wildcard}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"IS_SYNCGW_INSTALLED", "PARAMVALUE": "0", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"SSH_TERMINATE_DIALOG_OPT_FLAG", "PARAMVALUE": "1", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"IDAP_INSTALLED_FLAG", "PARAMVALUE":{{idap_micro_common_config['IDAP_INSTALLED_FLAG']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"IDAP_INSTALL_LIGHT", "PARAMVALUE":{{idap_micro_common_config['IDAP_INSTALL_LIGHT']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"ELASTIC_VERSION", "PARAMVALUE":{{idap_micro_common_config['ELASTIC_VERSION']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"HIVE_HADOOP_VERSION", "PARAMVALUE":{{idap_micro_common_config['HIVE_HADOOP_VERSION']}}, "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"PKI_ORGANISATION", "PARAMVALUE":"{{INTERNAL_HOST_DOMAIN}}", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"VAULT_TEMP_CERT_FLAG", "PARAMVALUE": "1", "CLUSTERID": {{idx + 1}}},
                    {"PARAMNAME":"POC_SYSTEM_ID", "PARAMVALUE": "{{POC_SYSTEM_ID}}", "CLUSTERID": {{idx + 1}}},
                  {% endfor %}
                ]
              }
        
        - name: Sending Update request for COMMON CONFIG
          uri:
            url: "http://{{cmsurl}}/cms/config?v=634844190505"
            headers:
              Connection: keep-alive
              Authorization: "Bearer {{cms_login_token}}"
              Accept: "application/json, text/plain, */*"
            method: POST
            body: "{{data}}"
            body_format: json
            return_content: yes
            timeout: 600
          register: response
          failed_when: response.json.code | int not in [200, 201]
        
        - name: update the task in status file
          lineinfile:
              path: "{{status_file}}"
              line: "micro_common_configuration"
        
      when: "'micro_common_configuration' not in status_check_list"
