---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: CHASSISINFO_GETALL
      uri:
        url: "http://{{ cmsurl }}/cms/config?v=1620913452992"
        method: POST
        headers:
          Connection: 'keep-alive'
          Authorization: "Bearer {{ cms_login_token }}"
          Accept: 'application/json, text/plain, */*'
        validate_certs: no
        body: {"context":"CHASSISINFO","action":"CHASSISINFO_GETALL"}
        body_format: json
      register: chassisinfo_get

    - name: Debug chassisinfo_get
      debug:
        msg: "{{ chassisinfo_get }}"

    - name: Extract chassis data
      set_fact:
        resp: "{{ chassisinfo_get | to_json | from_json | json_query('json.data[*]') }}"

    - name: Update chassis array substitution
      set_fact:
        update_chassis: >
          {"chassislist":[
          {% for i in chassis_list %}
            {% for item in i.chassisid %}
              {% set jq = "[? CHASSISID == `" + item.id|string()  + "`]" %}
              {% set count = resp | json_query(jq) | length %}
              {% if count > 0 %}
                {% for data in resp %}
                  {% if data.CHASSISID == item.id %}
                    {"context":"CHASSISINFO","action":"CHASSISINFO_UPDATE","actionObject":[{"KVM_HOST_IPADDRESS":"{{ item.host_ip }}","CHASSISID":{{ data.CHASSISID }},"IPADDRESS":"{{ item.kvm_ip }}", "CHASSISNAME":"{{ item.chassisname }}", "LOCATION":"{{ data.LOCATION }}", "RACKNUMBER":"{{ data.RACKNUMBER }}", "SHELFNUMBER":"{{ data.SHELFNUMBER }}","NUMOFSLOTS":"{{ data.NUMOFSLOTS }}", "ZIPCODE":"{{ data.ZIPCODE }}", "CITY":"{{ data.CITY }}", "CARRIERID":"{{ data.CARRIERID }}", "CHASSISTYPE":"{{ data.CHASSISTYPE }}" }]},
                  {% endif %}
                {% endfor %}
              {% else %}
                {"context":"CHASSISINFO","action":"CHASSISINFO_ADD","actionObject":[{"CHASSISID":"","CARRIERID":"{{ item.carrier_id}}","CHASSISNAME":"{{ item.chassisname }}","LOCATION":"{{ item.location }}","CITY":"{{ item.city}}","ZIPCODE":"{{ item.zipcode }}","RACKNUMBER":"{{ item.rack_number }}","SHELFNUMBER":"{{ item.shelf_number }}","NUMOFSLOTS":99,"CHASSISTYPE":"{{ item.chassis_type }}","CHASSISTYPE_DISPLAY":"2U Virtualized Chassis","IPADDRESS":"{{ item.kvm_ip }}","VMSTATUS_DISPLAY":"","KVM_HOST_IPADDRESS":"{{ item.host_ip }}","KVM_HOST_STATUS_DISPLAY":""}]},
              {% endif %}
            {% endfor %}
          {% endfor %}
          ]}

    - name: Debug update_chassis
      debug:
        msg: "{{ update_chassis }}"

    - name: CHASSISINFO_UPDATE
      uri:
        url: "http://{{ cmsurl }}/cms/networkmap?v=1620732259069"
        method: POST
        headers:
          Connection: 'keep-alive'
          Authorization: "Bearer {{ cms_login_token }}"
          Accept: 'application/json, text/plain, */*'
        validate_certs: no
        body: "{{ item }}"
        body_format: json
      register: chass_upd
      loop: "{{ update_chassis.chassislist | unique }}"
      when: dry_run == 0
      failed_when: chass_upd.json.code | int not in [200, 201]

    - name: Update the task in status file
      lineinfile:
        path: "{{ status_file }}"
        line: "update_chassis"
